### ISSUE TITLE
Can you add more transitions?

### ISSUE THREAD

**Issue by toshiba525** [xzripper/flet_navigator#15]
Is it possible to add more animations and transitions?

**Comment by xzripper** [comment]
Do you want to create your own animations and apply them or do you want me to add new ones?

**Comment by toshiba525** [comment]
1st. Can i create my own animation?
2nd. If you may plz add some.
BTW i love flet-navigator cuz it is really easier than using flet's built in routing.
Thanks

**Comment by xzripper** [comment]
Thanks so much for your support! I don't think it'll be too tricky to add custom animations. I'm planning to release a new version of Flet-Navigator tomorrow (UTC +3:00) with that feature. It would also be great if you could give me some ideas for animations you'd like to see in the navigator.

**Comment by toshiba525** [comment]
I recommend a sliding page from right to left when entering a new page and the opposite when going back, flipping tiles is another thing that would be nice, and many more!

**Comment by xzripper** [comment]
```python
def my_animation(control: Control, mult: float, smoothess: float) -> None:
    for angle in range(0, randint(80, 140), smoothess + 1):
        control.rotate = angle

        control.scale = mult

anim = NavigatorAnimation(NavigatorAnimation.CUSTOM, NavigatorAnimation.SMOOTHNESS_10);
anim.set_custom_animation(my_animation)

flet_navigator = VirtualFletNavigator(navigator_animation=anim)
```

What do you think? Isn't it complicated for newcomers?

**Comment by xzripper** [comment]
```python
def my_animation(control: Control, mult: float, smoothess: float) -> None:
    control.scale = Scale(scale=control.scale.scale if control.scale else 1)

    control.scale.scale += mult * 0.1

anim = NavigatorAnimation(NavigatorAnimation.CUSTOM, NavigatorAnimation.SMOOTHNESS_10);
anim.set_custom_animation(my_animation)

flet_navigator = VirtualFletNavigator(navigator_animation=anim)
```

Another fun custom animation.

![Aj4vj0s68N](https://github.com/user-attachments/assets/1f8a7263-d035-46f9-a294-055888b680a3)

**Comment by xzripper** [comment]
<a href="https://github.com/xzripper/flet_navigator/releases/tag/v2.8.5">V2.8.5</a> is released! Implemented custom animations (check documentation), fixed some animation issues, etc. Also I failed to implement sliding page or flipping tiles, because its impossible, here is why:
1. Can't implement sliding page because navigator has no ability to make IN animation after page loaded.
2. Can't implement sliding page because controls (widgets) position can be changed only in <a href="https://flet.dev/docs/controls/stack/">`Stack`</a>.
3. Can't implement flipping tiles because Flet has no ability to rotate controls by other axis than `Y` (or `P` if we are using `HPR`).

But its not over thought, you still can implement sliding page via custom animations, see Flet absolute positioning: https://flet.dev/docs/controls/stack/#absolute-positioning-inside-stack

Also FletNavigator is archived, i.e development is halted. But you can still push new issue and ask for help. Good luck!

**Comment by xzripper** [comment]
You can re-open this issue if you want.
